"""QgsTask-based classification worker.

Runs classification in the background using the QGIS task manager. Heavy
imports (torch, laspy, classifier core) are deferred to the ``run()``
method so creating the task does not pull them in.
"""

import traceback
from pathlib import Path

import numpy as np

from qgis.core import QgsTask

from ..config import TILE_DEFAULT_BUFFER_M
from ..core.backends import create_backend
from ..core.registry import get_model
from ..core.tiling import compute_tile_grid
from ..utils.compat import scoped_enum
from ..utils.las_units import resolve_units
from ..utils.las_utils import strip_copc_vlrs as _strip_copc_vlrs
from ..utils.logger import LOG_TAG, log_error, log_info, log_warning
from ..utils.model_manager import ModelManager
from ..utils.output_safety import (add_extra_dim_preserving_raw, atomic_output_path, validate_output_paths, validate_label_field,
                                   read_complete, checked_predictions, label_values, assign_labels,
                                   add_label_metadata, upgrade_header_preserving_fields,
                                   convert_points_preserving_fields)


# Lazy torch import (so module import is cheap)
_torch = None


def _get_torch():
    global _torch
    if _torch is None:
        from ..utils.venv_manager import ensure_venv_packages_available
        ensure_venv_packages_available()
        import torch
        _torch = torch
    return _torch


# ASPRS standard classification dimension name.
ASPRS_CLASSIFICATION_FIELD = "classification"

# Minimum LAS point record format that exposes a full 8-bit (0-255)
# classification field per the ASPRS LAS 1.4 specification. Older
# formats (0-5) only carry 5 bits and cannot encode codes > 31.
ASPRS_PF6 = 6


def _ensure_asprs_classification_capacity(las, laspy_module, max_code: int):
    """Return a LAS object whose point format can hold ``max_code``.

    The ASPRS LAS specification only guarantees a full classification
    range (0-255) in point record formats 6 and above. If the source
    file uses an older PRF and we need to write a code outside the
    5-bit range, transparently convert to PRF 6 / LAS 1.4 so the output
    is fully ASPRS-compliant.
    """
    if max_code <= 31:
        return las
    try:
        pf_id = las.point_format.id
    except Exception:
        return las
    if pf_id >= ASPRS_PF6:
        return las
    header = upgrade_header_preserving_fields(las.header, laspy_module)
    points = convert_points_preserving_fields(las.points, header.point_format,
                                               header.scales, header.offsets, laspy_module)
    return laspy_module.LasData(header, points)



# ---------------------------------------------------------------------------
# Output path + writer
# ---------------------------------------------------------------------------

def _resolve_output_path(
    input_path: Path, out_dir: Path, suffix: str,
) -> Path:
    """Pick the output path: LAS in -> LAS out, anything else -> LAZ.

    COPC inputs (``*.copc.laz``) are written as plain LAZ - the COPC
    spatial index is not regenerated by laspy.
    """
    stem = input_path.stem
    if stem.lower().endswith(".copc"):
        stem = stem[:-5]
    ext = ".las" if input_path.suffix.lower() == ".las" else ".laz"
    return out_dir / f"{stem}{suffix}{ext}"


def _write_las(las, out_path: Path, laspy_module) -> None:
    """Write a LasData object as plain LAS or LAZ based on extension."""
    with atomic_output_path(out_path) as temporary:
        kwargs = {}
        if out_path.suffix.lower() == ".laz":
            kwargs["laz_backend"] = laspy_module.LazBackend.LazrsParallel
        las.write(str(temporary), **kwargs)
        with laspy_module.open(str(temporary)) as check:
            if check.header.point_count != len(las.points):
                raise ValueError("Output point-count verification failed.")


# ---------------------------------------------------------------------------
# Tiling
# ---------------------------------------------------------------------------

def _compute_tile_grid(
    xy: np.ndarray, n_points: int,
    auto: bool, manual_tile_size_m: float | None,
) -> tuple[list[tuple[float, float, float, float]], float]:
    """Compute spatial tile bounds for an XY array.

    Returns (tiles, tile_size_m) where each tile is (x0, y0, x1, y1).
    Tiles cover the full XY extent without overlap (overlap is added
    separately as a buffer per tile when filtering points).
    """
    xmin, ymin = float(xy[:, 0].min()), float(xy[:, 1].min())
    xmax, ymax = float(xy[:, 0].max()), float(xy[:, 1].max())
    return compute_tile_grid(
        xmin, ymin, xmax, ymax, n_points, auto, manual_tile_size_m
    )


def _classify_tiled(
    pcd: np.ndarray,
    predict_fn,
    progress_callback,
    cancel_callback,
    auto: bool = True,
    tile_size_m: float | None = None,
    buffer_m: float = TILE_DEFAULT_BUFFER_M,
) -> np.ndarray | None:
    """Run ``predict_fn`` on ``pcd`` in spatial tiles with a buffer halo.

    ``predict_fn(xyz_m, progress_cb)`` returns one model class id per
    point (a loaded backend's ``predict``). Returns predictions aligned
    with the input points, or None if cancelled.
    """
    n = len(pcd)
    xy = pcd[:, :2]
    tiles, resolved_size = _compute_tile_grid(xy, n, auto, tile_size_m)
    n_tiles = len(tiles)

    log_info(
        f"Tiled inference: {n_tiles} tile(s), tile size "
        f"~{resolved_size:.0f} m, buffer {buffer_m:.0f} m."
    )

    predictions = np.zeros(n, dtype=np.int32)
    assigned = np.zeros(n, dtype=bool)

    for i, (tx0, ty0, tx1, ty1) in enumerate(tiles):
        if cancel_callback():
            return None

        bx0, by0 = tx0 - buffer_m, ty0 - buffer_m
        bx1, by1 = tx1 + buffer_m, ty1 + buffer_m

        in_buffer = (
            (xy[:, 0] >= bx0) & (xy[:, 0] <= bx1)
            & (xy[:, 1] >= by0) & (xy[:, 1] <= by1)
        )
        if not in_buffer.any():
            continue

        buffer_idx = np.where(in_buffer)[0]
        in_core_local = (
            (xy[buffer_idx, 0] >= tx0) & (xy[buffer_idx, 0] < tx1)
            & (xy[buffer_idx, 1] >= ty0) & (xy[buffer_idx, 1] < ty1)
        )

        def tile_progress(p, _i=i):
            # Map (0..100) within the tile to the overall progress range.
            overall = (_i + (p / 100.0)) / n_tiles * 100.0
            progress_callback(overall)

        try:
            tile_preds = predict_fn(pcd[buffer_idx], tile_progress)
        except InterruptedError:
            return None

        if tile_preds is None:
            raise ValueError(f"Tile {i + 1}/{n_tiles} returned no predictions.")
        tile_preds = checked_predictions(tile_preds, len(buffer_idx))

        core_global_idx = buffer_idx[in_core_local]
        predictions[core_global_idx] = tile_preds[in_core_local]
        assigned[core_global_idx] = True

        progress_callback(((i + 1) / n_tiles) * 100.0)

    # The grid covers the whole extent with half-open cores, so every
    # point belongs to exactly one core and this should never fire. If
    # it does (a tile returned nothing, NaN coordinates), say so plainly
    # rather than pretending a neighbour's prediction was used: these
    # points keep model id 0, which the caller reports as "unmapped ->
    # ASPRS 0" together with a count.
    if not assigned.all():
        raise ValueError(f"{int((~assigned).sum()):,} points were not covered by tile cores; no output published.")

    return predictions


def _empty_gpu_cache_safe():
    try:
        t = _get_torch()
        if t.cuda.is_available():
            t.cuda.empty_cache()
        mps = getattr(t.backends, "mps", None)
        if mps is not None and mps.is_available() and hasattr(t, "mps"):
            t.mps.empty_cache()
    except Exception:
        pass


class ClassificationTask(QgsTask):
    """Background task that runs the classifier over a list of files."""

    def __init__(self, files, out_dir, suffix, model_id, device, field_name,
                 tile_enabled=False, tile_auto=True,
                 tile_size_m=None, tile_buffer_m=TILE_DEFAULT_BUFFER_M,
                 tile_streaming=False, units_override=None):
        super().__init__("Classifying LiDAR point clouds",
                         scoped_enum(QgsTask, "Flag", "CanCancel"))
        # "auto" (read the CRS), "metre", "foot" or "us_foot"; see
        # utils.las_units. The model needs metres.
        self.units_override = units_override
        self.files = list(files)
        self.out_dir = Path(out_dir)
        self.suffix = suffix or "_classified"
        # The model (core.registry) brings its weights, its backend and
        # its class-id -> ASPRS mapping.
        self.spec = get_model(model_id)
        # "cuda", "mps" or "cpu" (see classifier_core.resolve_device).
        self.device = device
        self.field_name = field_name or ASPRS_CLASSIFICATION_FIELD
        self.class_mapping = self.spec.class_mapping

        self.tile_enabled = bool(tile_enabled)
        self.tile_auto = bool(tile_auto)
        self.tile_size_m = tile_size_m
        self.tile_buffer_m = float(TILE_DEFAULT_BUFFER_M if tile_buffer_m is None else tile_buffer_m)
        self.tile_streaming = bool(tile_streaming)

        self.output_files = []
        self.error_message = None
        self.current_file_name = ""
        # Set while a stage other than a file is running (weights download).
        self.status_text = ""
        self.files_processed = 0

    # ------------------------------------------------------------------
    def run(self) -> bool:
        backend = None
        try:
            import laspy
            _get_torch()  # ensures torch DLL path is set on Windows

            self.out_dir.mkdir(parents=True, exist_ok=True)

            total = len(self.files)
            if total == 0:
                return True

            planned_outputs = [_resolve_output_path(fp, self.out_dir, self.suffix) for fp in self.files]
            validate_output_paths(self.files, planned_outputs)

            manager = ModelManager(self.spec)
            if not self.spec.supports_device(self.device):
                self.error_message = (
                    f"{self.spec.display_name} does not run on '{self.device}' "
                    f"({self.spec.device_requirement_text()}). Choose another "
                    "model or compute device."
                )
                log_error(self.error_message)
                return False
            # First run of a model: fetch its weights now (no separate
            # download step for the user). The progress bar shows the
            # download, then restarts for the classification.
            if not manager.is_model_available():
                size_mb = self.spec.weights_size_mb

                def download_progress(received, total):
                    total = total if total > 0 else size_mb * 1024 * 1024
                    self.status_text = (
                        f"Downloading the {self.spec.short_name} weights "
                        f"(first use): {received / 1048576:.0f} / "
                        f"{total / 1048576:.0f} MB"
                    )
                    self.setProgress(min(99.0, 100.0 * received / total))

                self.status_text = (
                    f"Downloading the {self.spec.short_name} weights "
                    f"(first use, about {size_mb:.0f} MB)...")
                self.setProgress(0)
                try:
                    ok, msg = manager.ensure_available(
                        download_progress, self.isCanceled)
                except InterruptedError:
                    return False
                if not ok:
                    self.error_message = msg
                    log_error(msg)
                    return False
                self.status_text = ""
                self.setProgress(0)

            # Load the network once for the whole run; every tile of every
            # file goes through the same backend.
            backend = create_backend(
                self.spec, manager.get_model_path(), log=log_warning,
            )
            log_info(
                f"Model: {self.spec.display_name} on {self.device.upper()}"
            )
            backend.load(self.device)

            def predict_fn(xyz_m, progress_cb):
                return backend.predict(xyz_m, progress_cb, self.isCanceled)

            for i, fp in enumerate(self.files):
                if self.isCanceled():
                    return False

                self.current_file_name = fp.name
                self.files_processed = i

                log_info(f"Processing {fp.name} ({i + 1}/{total})")

                file_base = (i / total) * 100.0
                file_span = 100.0 / total
                self.setProgress(file_base + file_span * 0.05)

                out_path = _resolve_output_path(
                    fp, self.out_dir, self.suffix
                )

                # Safety: never overwrite the input file.
                try:
                    same = out_path.resolve() == fp.resolve()
                except Exception:
                    same = False
                if same:
                    msg = (
                        f"Refusing to overwrite the input file: "
                        f"{fp.name}. Choose a different output folder or "
                        "suffix."
                    )
                    log_error(msg)
                    self.error_message = msg
                    return False

                if out_path.exists():
                    log_warning(
                        f"Output {out_path.name} already exists - overwriting."
                    )

                try:
                    actual_path = self._process_one(
                        fp, out_path, predict_fn, laspy,
                        file_base, file_span,
                    )
                    if actual_path is not None:
                        self.output_files.append(actual_path)
                except InterruptedError:
                    log_info("Cancellation requested - stopping.")
                    return False
                except Exception as exc:
                    msg = f"Failed on {fp.name}: {exc}"
                    log_error(msg + "\n" + traceback.format_exc())
                    self.error_message = msg
                    return False

                self.setProgress(file_base + file_span)
                _empty_gpu_cache_safe()

            self.files_processed = total
            return True

        except Exception as exc:
            self.error_message = f"{exc}\n{traceback.format_exc()}"
            log_error(f"Classification error: {self.error_message}")
            _empty_gpu_cache_safe()
            return False
        finally:
            if backend is not None:
                try:
                    backend.unload()
                except Exception:
                    pass

    # ------------------------------------------------------------------
    def _can_stream(self) -> bool:
        """Return True iff streaming mode is enabled.

        The streaming path supports ASPRS / custom extra-byte fields
        and automatic LAS-1.4 / PRF 6 upgrade. No silent fallbacks.
        """
        return bool(self.tile_enabled and self.tile_streaming)

    # ------------------------------------------------------------------
    def _process_one_streaming(
        self, fp, out_path, predict_fn, laspy,
        file_base, file_span,
    ):
        """Streaming variant: process a single file with disk-backed tiling."""
        from .streaming_classifier import streaming_tiled_classify

        log_info(f"Streaming mode active for {fp.name}")

        def stream_progress(p):
            if self.isCanceled():
                raise InterruptedError()
            self.setProgress(file_base + file_span * (p / 100.0))

        field = (self.field_name or ASPRS_CLASSIFICATION_FIELD).strip()

        try:
            written = streaming_tiled_classify(
                input_path=fp,
                output_path=out_path,
                predict_fn=predict_fn,
                device=self.device,
                class_mapping=self.class_mapping,
                field_description=f"AI classification ({self.spec.display_name})",
                model_spec=self.spec,
                laspy_module=laspy,
                progress_callback=stream_progress,
                cancel_callback=self.isCanceled,
                field_name=field,
                tile_auto=self.tile_auto,
                tile_size_m=None if self.tile_auto else self.tile_size_m,
                buffer_m=self.tile_buffer_m,
                units_override=self.units_override,
            )
        except InterruptedError:
            raise
        return written

    # ------------------------------------------------------------------
    def _process_one(self, fp, out_path, predict_fn, laspy,
                     file_base, file_span):
        """Run inference on a single file and write the result."""
        # Streaming mode dispatch -------------------------------------------
        if self._can_stream():
            return self._process_one_streaming(
                fp, out_path, predict_fn, laspy,
                file_base, file_span,
            )

        # In-memory path -----------------------------------------------------
        validate_output_paths([fp], [out_path])
        with laspy.open(str(fp), laz_backend=laspy.LazBackend.LazrsParallel) as reader:
            field = validate_label_field(reader.header.point_format, self.field_name, laspy)
            las = read_complete(reader)

        if len(las.x) == 0:
            log_warning(f"Skipping {fp.name}: input has zero points.")
            return None

        # The model works in metres. US files are usually in US survey
        # feet; without this conversion every distance is 3.28x too
        # small for it and buildings come out as wires and towers.
        units = resolve_units(las.header, self.units_override)
        if units.angular:
            raise RuntimeError(
                f"{fp.name} is in geographic coordinates (degrees). The "
                "model needs projected coordinates: reproject the file (for "
                "example to the local UTM zone) and run again."
            )
        log_info(f"{fp.name}: coordinate units: {units.describe()}")
        pcd = units.apply(np.transpose(np.array([las.x, las.y, las.z])))

        def progress_cb(p):
            if self.isCanceled():
                raise InterruptedError()
            self.setProgress(file_base + file_span * (0.10 + p * 0.008))

        if self.tile_enabled:
            preds = _classify_tiled(
                pcd, predict_fn, progress_cb, self.isCanceled,
                auto=self.tile_auto,
                tile_size_m=self.tile_size_m,
                buffer_m=self.tile_buffer_m,
            )
        else:
            preds = predict_fn(pcd, progress_cb)

        if preds is None:
            raise ValueError(f"Classifier returned no results for {fp.name}; no output published.")

        self.setProgress(file_base + file_span * 0.92)

        preds = checked_predictions(preds, len(las.points))
        is_asprs_field = field == ASPRS_CLASSIFICATION_FIELD
        asprs_p = label_values(preds, self.class_mapping, raw_ids=not is_asprs_field)

        if is_asprs_field:
            try:
                max_code = int(asprs_p.max())
            except ValueError:
                max_code = 0
            las = _ensure_asprs_classification_capacity(las, laspy, max_code)
            las.classification = asprs_p.astype(np.uint8)
        elif field in las.point_format.dimension_names:
            assign_labels(las, field, asprs_p)
        else:
            add_extra_dim_preserving_raw(las, laspy.ExtraBytesParams(
                name=field, type="int32",
                description=f"AI classification ({self.spec.display_name})"[:32],
            ))
            assign_labels(las, field, asprs_p)

        add_label_metadata(las.header, self.spec, field)
        _strip_copc_vlrs(las)
        _write_las(las, out_path, laspy)
        return out_path

    # ------------------------------------------------------------------
    def cancel(self):  # noqa: N802 - QGIS API
        log_info("ClassificationTask: cancel requested.")
        super().cancel()


# Expose the tag used by external loggers for backwards compatibility.
TAG = LOG_TAG
