"""QgsTask-based classification worker.

Runs classification in the background using the QGIS task manager. Heavy
imports (torch, laspy, classifier core) are deferred to the ``run()``
method so creating the task does not pull them in.
"""

import math
import traceback
from pathlib import Path

import numpy as np

from qgis.core import QgsTask

from ..config import TILE_AUTO_TARGET_POINTS, TILE_DEFAULT_BUFFER_M
from ..utils.las_utils import strip_copc_vlrs as _strip_copc_vlrs
from ..utils.logger import LOG_TAG, log_error, log_info, log_warning


# Lazy torch import (so module import is cheap)
_torch = None


def _get_torch():
    global _torch
    if _torch is None:
        from ..utils.venv_manager import ensure_venv_packages_available
        ensure_venv_packages_available()
        import torch
        _torch = torch
    return _torch


# ASPRS standard classification dimension name.
ASPRS_CLASSIFICATION_FIELD = "classification"

# Minimum LAS point record format that exposes a full 8-bit (0-255)
# classification field per the ASPRS LAS 1.4 specification. Older
# formats (0-5) only carry 5 bits and cannot encode codes > 31.
ASPRS_PF6 = 6


def _ensure_asprs_classification_capacity(las, laspy_module, max_code: int):
    """Return a LAS object whose point format can hold ``max_code``.

    The ASPRS LAS specification only guarantees a full classification
    range (0-255) in point record formats 6 and above. If the source
    file uses an older PRF and we need to write a code outside the
    5-bit range, transparently convert to PRF 6 / LAS 1.4 so the output
    is fully ASPRS-compliant.
    """
    if max_code <= 31:
        return las
    try:
        pf_id = las.point_format.id
    except Exception:
        return las
    if pf_id >= ASPRS_PF6:
        return las
    log_info(
        f"Upgrading point format {pf_id} -> {ASPRS_PF6} (LAS 1.4) "
        f"to encode ASPRS class code {max_code} per the LAS standard."
    )
    return laspy_module.convert(
        las, point_format_id=ASPRS_PF6, file_version="1.4"
    )


# ---------------------------------------------------------------------------
# Output path + writer
# ---------------------------------------------------------------------------

def _resolve_output_path(
    input_path: Path, out_dir: Path, suffix: str,
) -> Path:
    """Pick the output path: LAS in -> LAS out, anything else -> LAZ.

    COPC inputs (``*.copc.laz``) are written as plain LAZ - the COPC
    spatial index is not regenerated by laspy.
    """
    stem = input_path.stem
    if stem.lower().endswith(".copc"):
        stem = stem[:-5]
    ext = ".las" if input_path.suffix.lower() == ".las" else ".laz"
    return out_dir / f"{stem}{suffix}{ext}"


def _write_las(las, out_path: Path, laspy_module) -> None:
    """Write a LasData object as plain LAS or LAZ based on extension."""
    if out_path.suffix.lower() == ".laz":
        las.write(
            str(out_path), laz_backend=laspy_module.LazBackend.LazrsParallel
        )
    else:
        las.write(str(out_path))


# ---------------------------------------------------------------------------
# Tiling
# ---------------------------------------------------------------------------

def _compute_tile_grid(
    xy: np.ndarray, n_points: int,
    auto: bool, manual_tile_size_m: float | None,
) -> tuple[list[tuple[float, float, float, float]], float]:
    """Compute spatial tile bounds for an XY array.

    Returns (tiles, tile_size_m) where each tile is (x0, y0, x1, y1).
    Tiles cover the full XY extent without overlap (overlap is added
    separately as a buffer per tile when filtering points).
    """
    xmin, ymin = float(xy[:, 0].min()), float(xy[:, 1].min())
    xmax, ymax = float(xy[:, 0].max()), float(xy[:, 1].max())
    width = max(xmax - xmin, 1.0)
    height = max(ymax - ymin, 1.0)

    if auto:
        n_tiles_needed = max(1, math.ceil(n_points / TILE_AUTO_TARGET_POINTS))
        side = max(1, math.ceil(math.sqrt(n_tiles_needed)))
        tile_size_m = max(width, height) / side
    else:
        tile_size_m = float(manual_tile_size_m or 500.0)

    # See the equivalent comment in streaming_classifier._grid_from_bounds:
    # nudge the upper bounds so the half-open core [lo, hi) still
    # captures points exactly at xmax/ymax.
    eps_x = max(1e-6, abs(xmax - xmin) * 1e-9)
    eps_y = max(1e-6, abs(ymax - ymin) * 1e-9)
    xmax_eff = xmax + eps_x
    ymax_eff = ymax + eps_y

    tiles: list[tuple[float, float, float, float]] = []
    y = ymin
    while y < ymax_eff:
        x = xmin
        while x < xmax_eff:
            tiles.append(
                (x, y, min(x + tile_size_m, xmax_eff),
                 min(y + tile_size_m, ymax_eff))
            )
            x += tile_size_m
        y += tile_size_m
    return tiles, tile_size_m


def _classify_tiled(
    pcd: np.ndarray,
    classifier_fn,
    config_path: str,
    model_path: str,
    use_cuda: bool,
    progress_callback,
    cancel_callback,
    auto: bool = True,
    tile_size_m: float | None = None,
    buffer_m: float = TILE_DEFAULT_BUFFER_M,
) -> np.ndarray | None:
    """Run the classifier on ``pcd`` in spatial tiles with a buffer halo.

    Returns predictions aligned with the input points, or None if cancelled.
    """
    n = len(pcd)
    xy = pcd[:, :2]
    tiles, resolved_size = _compute_tile_grid(xy, n, auto, tile_size_m)
    n_tiles = len(tiles)

    log_info(
        f"Tiled inference: {n_tiles} tile(s), tile size "
        f"~{resolved_size:.0f} m, buffer {buffer_m:.0f} m."
    )

    predictions = np.zeros(n, dtype=np.int32)
    assigned = np.zeros(n, dtype=bool)

    for i, (tx0, ty0, tx1, ty1) in enumerate(tiles):
        if cancel_callback():
            return None

        bx0, by0 = tx0 - buffer_m, ty0 - buffer_m
        bx1, by1 = tx1 + buffer_m, ty1 + buffer_m

        in_buffer = (
            (xy[:, 0] >= bx0) & (xy[:, 0] <= bx1)
            & (xy[:, 1] >= by0) & (xy[:, 1] <= by1)
        )
        if not in_buffer.any():
            continue

        buffer_idx = np.where(in_buffer)[0]
        in_core_local = (
            (xy[buffer_idx, 0] >= tx0) & (xy[buffer_idx, 0] < tx1)
            & (xy[buffer_idx, 1] >= ty0) & (xy[buffer_idx, 1] < ty1)
        )

        def tile_progress(p, _i=i):
            # Map (0..100) within the tile to the overall progress range.
            overall = (_i + (p / 100.0)) / n_tiles * 100.0
            progress_callback(overall)

        try:
            tile_preds = classifier_fn(
                config_path, pcd[buffer_idx], model_path,
                if_bottom_only=False, use_efficient=True,
                use_cuda=use_cuda, progress_callback=tile_progress,
            )
        except InterruptedError:
            return None

        if tile_preds is None:
            log_warning(f"Tile {i + 1}/{n_tiles} returned no predictions.")
            continue

        core_global_idx = buffer_idx[in_core_local]
        predictions[core_global_idx] = tile_preds[in_core_local]
        assigned[core_global_idx] = True

        progress_callback(((i + 1) / n_tiles) * 100.0)

    # Edge effect: any point near the global bounds may have ended up
    # outside every core but inside at least one buffer. Run a last
    # cleanup pass for unassigned points (rare, < 0.1%).
    if not assigned.all():
        log_info(
            f"Filling {(~assigned).sum()} unassigned point(s) via nearest "
            "tile prediction."
        )
        # Cheap fallback: use 0 (unclassified) for any remaining holes.
        # These points are by construction outside all tile cores, so
        # they were never part of any tile inference.
        predictions[~assigned] = 0

    return predictions


def _empty_gpu_cache_safe():
    try:
        t = _get_torch()
        if t.cuda.is_available():
            t.cuda.empty_cache()
    except Exception:
        pass


class ClassificationTask(QgsTask):
    """Background task that runs the classifier over a list of files."""

    def __init__(self, files, out_dir, suffix, config_path, model_path,
                 use_cuda, field_name, class_mapping,
                 tile_enabled=False, tile_auto=True,
                 tile_size_m=None, tile_buffer_m=TILE_DEFAULT_BUFFER_M,
                 tile_streaming=False):
        super().__init__("Classifying LiDAR point clouds", QgsTask.CanCancel)
        self.files = list(files)
        self.out_dir = Path(out_dir)
        self.suffix = suffix or "_classified"
        self.config_path = config_path
        self.model_path = model_path
        self.use_cuda = use_cuda
        self.field_name = field_name or ASPRS_CLASSIFICATION_FIELD
        self.class_mapping = class_mapping

        self.tile_enabled = bool(tile_enabled)
        self.tile_auto = bool(tile_auto)
        self.tile_size_m = tile_size_m
        self.tile_buffer_m = float(tile_buffer_m or TILE_DEFAULT_BUFFER_M)
        self.tile_streaming = bool(tile_streaming)

        self.output_files = []
        self.error_message = None
        self.current_file_name = ""
        self.files_processed = 0

    # ------------------------------------------------------------------
    def run(self) -> bool:
        try:
            import laspy
            _get_torch()  # ensures torch DLL path is set on Windows
            from ..core.classifier_core import filterPoints

            self.out_dir.mkdir(parents=True, exist_ok=True)

            total = len(self.files)
            if total == 0:
                return True

            for i, fp in enumerate(self.files):
                if self.isCanceled():
                    return False

                self.current_file_name = fp.name
                self.files_processed = i

                log_info(f"Processing {fp.name} ({i + 1}/{total})")

                file_base = (i / total) * 100.0
                file_span = 100.0 / total
                self.setProgress(file_base + file_span * 0.05)

                out_path = _resolve_output_path(
                    fp, self.out_dir, self.suffix
                )

                # Safety: never overwrite the input file.
                try:
                    same = out_path.resolve() == fp.resolve()
                except Exception:
                    same = False
                if same:
                    msg = (
                        f"Refusing to overwrite the input file: "
                        f"{fp.name}. Choose a different output folder or "
                        "suffix."
                    )
                    log_error(msg)
                    self.error_message = msg
                    return False

                if out_path.exists():
                    log_warning(
                        f"Output {out_path.name} already exists - overwriting."
                    )

                try:
                    actual_path = self._process_one(
                        fp, out_path, filterPoints, laspy,
                        file_base, file_span,
                    )
                    if actual_path is not None:
                        self.output_files.append(actual_path)
                except InterruptedError:
                    log_info("Cancellation requested - stopping.")
                    return False
                except Exception as exc:
                    msg = f"Failed on {fp.name}: {exc}"
                    log_error(msg + "\n" + traceback.format_exc())
                    self.error_message = msg
                    return False

                self.setProgress(file_base + file_span)
                _empty_gpu_cache_safe()

            self.files_processed = total
            return True

        except Exception as exc:
            self.error_message = f"{exc}\n{traceback.format_exc()}"
            log_error(f"Classification error: {self.error_message}")
            _empty_gpu_cache_safe()
            return False

    # ------------------------------------------------------------------
    def _can_stream(self) -> bool:
        """Return True iff streaming mode is enabled.

        The streaming path supports ASPRS / custom extra-byte fields
        and automatic LAS-1.4 / PRF 6 upgrade. No silent fallbacks.
        """
        return bool(self.tile_enabled and self.tile_streaming)

    # ------------------------------------------------------------------
    def _process_one_streaming(
        self, fp, out_path, filter_fn, laspy,
        file_base, file_span,
    ):
        """Streaming variant: process a single file with disk-backed tiling."""
        from .streaming_classifier import streaming_tiled_classify

        log_info(f"Streaming mode active for {fp.name}")

        def stream_progress(p):
            if self.isCanceled():
                raise InterruptedError()
            self.setProgress(file_base + file_span * (p / 100.0))

        field = (self.field_name or ASPRS_CLASSIFICATION_FIELD).strip()

        try:
            written = streaming_tiled_classify(
                input_path=fp,
                output_path=out_path,
                classifier_fn=filter_fn,
                config_path=self.config_path,
                model_path=self.model_path,
                use_cuda=self.use_cuda,
                class_mapping=self.class_mapping,
                laspy_module=laspy,
                progress_callback=stream_progress,
                cancel_callback=self.isCanceled,
                field_name=field,
                tile_auto=self.tile_auto,
                tile_size_m=None if self.tile_auto else self.tile_size_m,
                buffer_m=self.tile_buffer_m,
            )
        except InterruptedError:
            raise
        return written

    # ------------------------------------------------------------------
    def _process_one(self, fp, out_path, filter_fn, laspy,
                     file_base, file_span):
        """Run inference on a single file and write the result."""
        # Streaming mode dispatch -------------------------------------------
        if self._can_stream():
            return self._process_one_streaming(
                fp, out_path, filter_fn, laspy,
                file_base, file_span,
            )

        # In-memory path -----------------------------------------------------
        with laspy.open(str(fp), laz_backend=laspy.LazBackend.LazrsParallel) as reader:
            las = reader.read()

        if len(las.x) == 0:
            log_warning(f"Skipping {fp.name}: input has zero points.")
            return None

        pcd = np.transpose(np.array([las.x, las.y, las.z]))

        def progress_cb(p):
            if self.isCanceled():
                raise InterruptedError()
            self.setProgress(file_base + file_span * (0.10 + p * 0.008))

        if self.tile_enabled:
            preds = _classify_tiled(
                pcd, filter_fn, self.config_path, self.model_path,
                self.use_cuda, progress_cb, self.isCanceled,
                auto=self.tile_auto,
                tile_size_m=self.tile_size_m,
                buffer_m=self.tile_buffer_m,
            )
        else:
            preds = filter_fn(
                self.config_path, pcd, self.model_path,
                if_bottom_only=False, use_efficient=True,
                use_cuda=self.use_cuda, progress_callback=progress_cb,
            )

        if preds is None:
            log_warning(f"Classifier returned no results for {fp.name}")
            return None

        self.setProgress(file_base + file_span * 0.92)

        asprs_p = np.zeros_like(preds, dtype=np.int32)
        for mid, info in self.class_mapping.items():
            asprs_p[preds == mid] = info.asprs_code

        # Surface predictions that fall outside the configured mapping
        # rather than silently sending them to ASPRS 0.
        mapped_ids = list(self.class_mapping.keys())
        if mapped_ids:
            unmapped = ~np.isin(preds, mapped_ids)
            unmapped_count = int(unmapped.sum())
            if unmapped_count:
                missing_ids = sorted(np.unique(preds[unmapped]).tolist())
                log_warning(
                    f"{unmapped_count:,} prediction(s) had model IDs not "
                    f"present in the class mapping (IDs: {missing_ids}); "
                    "they were set to ASPRS 0."
                )

        self.setProgress(file_base + file_span * 0.96)

        field = (self.field_name or "").strip() or ASPRS_CLASSIFICATION_FIELD
        is_asprs_field = field.lower() == ASPRS_CLASSIFICATION_FIELD

        if is_asprs_field:
            try:
                max_code = int(asprs_p.max())
            except ValueError:
                max_code = 0
            las = _ensure_asprs_classification_capacity(las, laspy, max_code)
            las.classification = asprs_p.astype(np.uint8)
        elif field in las.point_format.dimension_names:
            setattr(las, field, asprs_p)
        else:
            las.add_extra_dim(laspy.ExtraBytesParams(
                name=field, type="int32",
                description="AI Classification (3D SegFormer / TreeAIBox)",
            ))
            setattr(las, field, asprs_p)

        _strip_copc_vlrs(las)
        _write_las(las, out_path, laspy)
        return out_path

    # ------------------------------------------------------------------
    def cancel(self):  # noqa: N802 - QGIS API
        log_info("ClassificationTask: cancel requested.")
        super().cancel()


# Expose the tag used by external loggers for backwards compatibility.
TAG = LOG_TAG
